/**
 * Generates `src/styles/depth-tokens.css` from `src/config/depth-bands.ts`.
 *
 * Depth colours come only from the config. Tailwind needs static
 * CSS, so rather than hand-copying the hexes (which would let the two drift apart)
 * we generate them. `src/config/depth-bands.test.ts` asserts the committed file
 * still matches the config, so CI fails if someone edits one without the other.
 */
import { DEPTH_BANDS } from "../src/config/depth-bands.ts";

export function renderDepthTokens(): string {
  const line = (name: string, value: string): string =>
    `  --color-${name}: ${value};`;
  const light = DEPTH_BANDS.flatMap((b) => [
    line(b.token, b.color.light),
    line(`${b.token}-on`, b.on.light),
    line(`${b.token}-border`, b.border.light),
  ]);
  const dark = DEPTH_BANDS.flatMap((b) => [
    line(b.token, b.color.dark),
    line(`${b.token}-on`, b.on.dark),
    line(`${b.token}-border`, b.border.dark),
  ]);

  return `/*
 * GENERATED by \`pnpm tokens:generate\` from src/config/depth-bands.ts — do not edit.
 *
 * These are semantic tokens, not theme colours: no theme may override them.
 * The ramp is validated by \`pnpm check:cvd\`.
 */
@theme static {
${light.join("\n")}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${dark.map((l) => "  " + l).join("\n")}
  }
}

:root[data-theme='dark'] {
${dark.join("\n")}
}
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { writeFileSync } = await import("node:fs");
  const target = new URL("../src/styles/depth-tokens.css", import.meta.url);
  writeFileSync(target, renderDepthTokens());
  console.log(
    `✓ wrote src/styles/depth-tokens.css (${DEPTH_BANDS.length} bands)`,
  );
}
